export const actionType = {
  TODO_LOADING: "TODO_LOADING",
  TODO_SUCCESS: "TODO_SUCCESS",
  TODO_FAILURE: "TODO_FAILURE",
  TODO_RESET: "TODO_RESET",
  TODO_ADD: "TODO_ADD",
  TODO_DELETE: "TODO_DELETE",
  TODO_UPDATE: "TODO_UPDATE",
  TODO_COMPLETE: "TODO_COMPLETE",
};
